#pragma once

#ifndef ODEN_KONBU_CLAZY_LIMITS
#define ODEN_KONBU_CLAZY_LIMITS

//
// マクロ定義
//

// 実引数の数
#ifndef KONBU_CLAZY_ARG_LIMIT
#	define KONBU_CLAZY_ARG_LIMIT 3
#endif

// オペランドの数
#ifndef KONBU_CLAZY_OPERAND_LIMIT
#	define KONBU_CLAZY_OPERAND_LIMIT 5
#endif

// コンストラクタ引数の数
#ifndef KONBU_CLAZY_CTOR_LIMIT
#	define KONBU_CLAZY_CTOR_LIMIT KONBU_CLAZY_OPERAND_LIMIT
#else
#	if KONBU_CLAZY_CTOR_LIMIT < KONBU_CLAZY_OPERAND_LIMIT
#		define KONBU_CLAZY_CTOR_LIMIT KONBU_CLAZY_OPERAND_LIMIT
#	endif
#endif

// ローカル変数の合計の数
#ifndef KONBU_CLAZY_LOCAL_LIMIT
#	define KONBU_CLAZY_LOCAL_LIMIT 10
#endif

// fusionとの調整
#include <boost/fusion/container/vector/limits.hpp>
#if KONBU_CLAZY_ARG_LIMIT > KONBU_CLAZY_OPERAND_LIMIT
#	define KONBU_CLAZY_LIMIT_UPPER_BOUND KONBU_CLAZY_ARG_LIMIT
#else
#	define KONBU_CLAZY_LIMIT_UPPER_BOUND KONBU_CLAZY_CTOR_LIMIT
#endif
#if KONBU_CLAZY_LIMIT_UPPER_BOUND > FUSION_MAX_VECTOR_SIZE
#	define FUSION_MAX_VECTOR_SIZE KONBU_CLAZY_LIMIT_UPPER_BOUND
#endif

#if KONBU_CLAZY_LOCAL_LIMIT > FUSION_MAX_MAP_SIZE
#	define FUSION_MAX_MAP_SIZE KONBU_CLAZY_LOCAL_LIMIT
#endif

#endif